# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-05 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(max_length=64)),
                ('number_of_people', models.SmallIntegerField(null=True)),
                ('price', models.SmallIntegerField(null=True)),
                ('content', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.IntegerField(choices=[(1, 'mazowieckie'), (2, 'śląskie'), (3, 'wielkopolskie'), (4, 'małopolskie'), (5, 'dolnośląskie'), (6, 'łódzkie'), (7, 'pomorskie'), (8, 'lubelskie'), (9, 'podkarpackie'), (10, 'kujawsko-pomorskie'), (11, 'zachodniopomorskie'), (12, 'warmińsko-mazurskie'), (13, 'świętokrzyskie'), (14, 'podlaskie'), (15, 'lubuskie'), (16, 'opolskie')])),
            ],
        ),
        migrations.AddField(
            model_name='band',
            name='region',
            field=models.ManyToManyField(to='classifieds.Region'),
        ),
    ]
