# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-05 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='region',
        ),
        migrations.AddField(
            model_name='region',
            name='name',
            field=models.CharField(default='Radom', max_length=64),
            preserve_default=False,
        ),
    ]
