# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-05 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0002_auto_20170705_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
