# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-05 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0003_auto_20170705_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(max_length=124)),
                ('number_of_people', models.SmallIntegerField(null=True)),
                ('price', models.SmallIntegerField(null=True)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('region', models.ManyToManyField(to='classifieds.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=124)),
                ('number_of_people', models.SmallIntegerField(null=True)),
                ('price', models.SmallIntegerField(null=True)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('region', models.ManyToManyField(to='classifieds.Region')),
            ],
        ),
        migrations.AlterField(
            model_name='band',
            name='band_name',
            field=models.CharField(max_length=124),
        ),
    ]
