# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-05 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0004_auto_20170705_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
