# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-06 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0008_auto_20170706_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='massageband',
            old_name='text',
            new_name='massage_band',
        ),
    ]
