# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-07 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0009_auto_20170706_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifieds.Region')),
            ],
            options={
                'ordering': ['region', 'name'],
            },
        ),
    ]
